### ISSUE TITLE
Todo List

### ISSUE THREAD

**Issue by novolog** [novolog/RigNewton#1]
- [x] Ability to get RPM from Assetto Corsa
- [ ] Ability to send a constant sine wave to a single audio output
- [ ] The sine wave's frequency must be linked to the RPM value
- [ ] The sine wave's frequency is using a different range than the RPM value (assume max 10000RPM and 800Hz)
- [ ] The output level must be calculated on the RPM value.
- [ ] Use JSON config file for  RPM range, output frequency.
